services:
  backend:
    image: rishabhpahwa/superpatch-backend
    container_name: superpatch-backend
    hostname: superpatch-backend
    ports:
      - "3200:3200"
      - "5173:5173"  # Frontend 
    restart: unless-stopped

  frontend:
    image: rishabhpahwa/superpatch-frontend
    container_name: superpatch-frontend
    network_mode: "service:backend" 
    depends_on:
      - backend
    restart: unless-stopped
